apiVersion: v1
kind: Service
metadata:
  name: film-review-analyzer-service
spec:
  selector:
    app: film-review-analyzer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort